export const TOKOPEDIA_FILTER_SORT_QUERY_RESPONSE = {
  "data": {
    "filter_sort_product": {
      "data": {
        "filter": [
          {
            "title": "Durasi Pengiriman",
            "template_name": "",
            "search": {
              "searchable": 0,
              "placeholder": "",
              "__typename": "DAFilterSearch",
            },
            "options": [
              {
                "name": "Instan",
                "Description": "",
                "key": "shipping_child",
                "icon": "",
                "value": "nearby,28,37",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": true,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "Same Day",
                "Description": "",
                "key": "shipping_child",
                "icon": "",
                "value": "nearby,20,24,49",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": true,
                "__typename": "DAFilterOptions",
              },
            ],
            "__typename": "DAFilterType",
          },
          {
            "title": "Lokasi",
            "template_name": "template_location",
            "search": {
              "searchable": 1,
              "placeholder": "Cari Lokasi",
              "__typename": "DAFilterSearch",
            },
            "options": [
              {
                "name": "Kab. Tangerang",
                "Description": "",
                "key": "fcity",
                "icon": "",
                "value": "144",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
            ],
            "__typename": "DAFilterType",
          },
          {
            "title": "Jenis toko",
            "template_name": "",
            "search": {
              "searchable": 0,
              "placeholder": "",
              "__typename": "DAFilterSearch",
            },
            "options": [
              {
                "name": "Official Store",
                "Description": "",
                "key": "shop_tier",
                "icon": "https://ecs7.tokopedia.net/img/autocomplete/ic_os.png",
                "value": "2",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "Power Merchant Pro",
                "Description": "",
                "key": "shop_tier",
                "icon":
                  "https://images.tokopedia.net/img/goldmerchant/pm_activation/badge/Power%20Merchant%20Pro.png",
                "value": "3",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "Power Merchant",
                "Description": "",
                "key": "shop_tier",
                "icon": "https://ecs7.tokopedia.net/img/autocomplete/ic_pm.png",
                "value": "1",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
            ],
            "__typename": "DAFilterType",
          },
          {
            "title": "Harga",
            "template_name": "template_price",
            "search": {
              "searchable": 0,
              "placeholder": "",
              "__typename": "DAFilterSearch",
            },
            "options": [
              {
                "name": "Harga Minimum",
                "Description": "",
                "key": "pmin",
                "icon": "",
                "value": "0",
                "inputType": "textbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": false,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "Harga Maksimum",
                "Description": "",
                "key": "pmax",
                "icon": "",
                "value": "",
                "inputType": "textbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": false,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "",
                "Description": "",
                "key": "pmin-pmax",
                "icon": "",
                "value": "",
                "inputType": "slider",
                "totalData": "",
                "valMax": "1000000000",
                "valMin": "100",
                "hexColor": "",
                "child": [],
                "isPopular": false,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
            ],
            "__typename": "DAFilterType",
          },
          {
            "title": "Rating",
            "template_name": "template_rating",
            "search": {
              "searchable": 0,
              "placeholder": "",
              "__typename": "DAFilterSearch",
            },
            "options": [
              {
                "name": "4 Keatas",
                "Description": "",
                "key": "rt",
                "icon": "",
                "value": "4,5",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
            ],
            "__typename": "DAFilterType",
          },
          {
            "title": "Penawaran",
            "template_name": "template_offer",
            "search": {
              "searchable": 0,
              "placeholder": "",
              "__typename": "DAFilterSearch",
            },
            "options": [
              {
                "name": "Cashback",
                "Description":
                  "Dapatkan uang kembalian untuk bayar belanja berikutnya",
                "key": "cashbackm",
                "icon": "",
                "value": "true",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "Harga Grosir",
                "Description":
                  "Beli banyak lebih murah, tersedia layanan pengiriman beragam",
                "key": "wholesale",
                "icon": "",
                "value": "true",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
            ],
            "__typename": "DAFilterType",
          },
          {
            "title": "Layanan Tokopedia",
            "template_name": "layanan_tokopedia",
            "search": {
              "searchable": 0,
              "placeholder": "",
              "__typename": "DAFilterSearch",
            },
            "options": [
              {
                "name": "Dilayani Tokopedia",
                "Description": "",
                "key": "is_fulfillment",
                "icon":
                  "https://images.tokopedia.net/img/restriction-engine/bebas-ongkir/DilayaniTokopedia_Icon.png",
                "value": "true",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
            ],
            "__typename": "DAFilterType",
          },
          {
            "title": "Kategori",
            "template_name": "template_category",
            "search": {
              "searchable": 0,
              "placeholder": "",
              "__typename": "DAFilterSearch",
            },
            "options": [
              {
                "name": "Olahraga",
                "Description": "",
                "key": "sc",
                "icon":
                  "https://ecs7.tokopedia.net/img/WgKiGm/2021/6/23/13b2543c-6b80-4c11-956e-8711a6717b08.png",
                "value": "62",
                "inputType": "checkbox",
                "totalData": "8",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [
                  {
                    "key": "sc",
                    "value": "1404",
                    "name": "Sepeda",
                    "icon":
                      "https://ecs7.tokopedia.net/img/attachment/2020/3/19/82120085/82120085_d6fff71e-edb5-4764-8bfa-9175aa99a604.png",
                    "inputType": "checkbox",
                    "totalData": "8",
                    "child": [
                      {
                        "key": "sc",
                        "value": "3497",
                        "name": "Sepeda Balap",
                        "icon":
                          "https://ecs7.tokopedia.net/img/attachment/2019/9/21/3497/3497_beb326e6-7b2c-47c9-b070-453c56fe5aa4.png",
                        "inputType": "checkbox",
                        "totalData": "5",
                        "child": [],
                        "__typename": "DAChildCategory",
                      },
                      {
                        "key": "sc",
                        "value": "1508",
                        "name": "Spare Part Sepeda",
                        "icon":
                          "https://ecs7.tokopedia.net/img/attachment/2019/7/8/1508/1508_e52c58a7-c03d-4a1c-bc5b-f1e1bf295db0.png",
                        "inputType": "checkbox",
                        "totalData": "1",
                        "child": [],
                        "__typename": "DAChildCategory",
                      },
                      {
                        "key": "sc",
                        "value": "3508",
                        "name": "Aksesoris Sepeda",
                        "icon":
                          "https://ecs7.tokopedia.net/img/attachment/2019/9/23/3508/3508_a405dc64-dfad-49c1-9b2b-5a647f0ab2a8.png",
                        "inputType": "checkbox",
                        "totalData": "1",
                        "child": [],
                        "__typename": "DAChildCategory",
                      },
                      {
                        "key": "sc",
                        "value": "1406",
                        "name": "Frame Sepeda",
                        "icon":
                          "https://ecs7.tokopedia.net/img/attachment/2019/7/8/1406/1406_73cf5342-3d00-49cb-8ba7-982b390dd7f1.png",
                        "inputType": "checkbox",
                        "totalData": "1",
                        "child": [],
                        "__typename": "DAChildCategory",
                      },
                    ],
                    "isPopular": true,
                    "__typename": "DAChildCategory",
                  },
                ],
                "isPopular": false,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
            ],
            "__typename": "DAFilterType",
          },
          {
            "title": "Kondisi",
            "template_name": "",
            "search": {
              "searchable": 0,
              "placeholder": "",
              "__typename": "DAFilterSearch",
            },
            "options": [
              {
                "name": "Baru",
                "Description": "",
                "key": "condition",
                "icon": "",
                "value": "1",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "Bekas",
                "Description": "",
                "key": "condition",
                "icon": "",
                "value": "2",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
            ],
            "__typename": "DAFilterType",
          },
          {
            "title": "Pengiriman",
            "template_name": "",
            "search": {
              "searchable": 0,
              "placeholder": "",
              "__typename": "DAFilterSearch",
            },
            "options": [
              {
                "name": "SiCepat",
                "Description": "",
                "key": "shipping",
                "icon": "",
                "value": "11",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "Anteraja",
                "Description": "",
                "key": "shipping",
                "icon": "",
                "value": "23",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "GoSend",
                "Description": "",
                "key": "shipping",
                "icon": "",
                "value": "10",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "GrabExpress",
                "Description": "",
                "key": "shipping",
                "icon": "",
                "value": "13",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "Paxel",
                "Description": "",
                "key": "shipping",
                "icon": "",
                "value": "28",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": false,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "JNE",
                "Description": "",
                "key": "shipping",
                "icon": "",
                "value": "1",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": false,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "Kurir Rekomendasi",
                "Description": "",
                "key": "shipping",
                "icon": "",
                "value": "26",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": false,
                "isNew": true,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "TIKI",
                "Description": "",
                "key": "shipping",
                "icon": "",
                "value": "2",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": false,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "J&T",
                "Description": "",
                "key": "shipping",
                "icon": "",
                "value": "14",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": false,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "Lion Parcel",
                "Description": "",
                "key": "shipping",
                "icon": "",
                "value": "24",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": false,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "Ninja Express",
                "Description": "",
                "key": "shipping",
                "icon": "",
                "value": "12",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": false,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "Pos Indonesia",
                "Description": "",
                "key": "shipping",
                "icon": "",
                "value": "4",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": false,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "Wahana",
                "Description": "",
                "key": "shipping",
                "icon": "",
                "value": "6",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": false,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "REX",
                "Description": "",
                "key": "shipping",
                "icon": "",
                "value": "16",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": false,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
            ],
            "__typename": "DAFilterType",
          },
          {
            "title": "Warna",
            "template_name": "template_color",
            "search": {
              "searchable": 0,
              "placeholder": "Cari Warna",
              "__typename": "DAFilterSearch",
            },
            "options": [
              {
                "name": "Biru",
                "Description": "",
                "key": "variants",
                "icon": "",
                "value": "5",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "#1d6cbb",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
            ],
            "__typename": "DAFilterType",
          },
          {
            "title": "Terakhir ditambahkan",
            "template_name": "",
            "search": {
              "searchable": 0,
              "placeholder": "",
              "__typename": "DAFilterSearch",
            },
            "options": [
              {
                "name": "7 Hari",
                "Description": "",
                "key": "latest_product",
                "icon": "",
                "value": "7",
                "inputType": "radio",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "14 Hari",
                "Description": "",
                "key": "latest_product",
                "icon": "",
                "value": "14",
                "inputType": "radio",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "1 Bulan",
                "Description": "",
                "key": "latest_product",
                "icon": "",
                "value": "30",
                "inputType": "radio",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "3 Bulan",
                "Description": "",
                "key": "latest_product",
                "icon": "",
                "value": "90",
                "inputType": "radio",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
            ],
            "__typename": "DAFilterType",
          },
          {
            "title": "Lainnya",
            "template_name": "",
            "search": {
              "searchable": 0,
              "placeholder": "",
              "__typename": "DAFilterSearch",
            },
            "options": [
              {
                "name": "Pre Order",
                "Description": "",
                "key": "preorder",
                "icon": "",
                "value": "true",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
              {
                "name": "Ready Stock",
                "Description": "",
                "key": "preorder",
                "icon": "",
                "value": "false",
                "inputType": "checkbox",
                "totalData": "",
                "valMax": "",
                "valMin": "",
                "hexColor": "",
                "child": [],
                "isPopular": true,
                "isNew": false,
                "__typename": "DAFilterOptions",
              },
            ],
            "__typename": "DAFilterType",
          },
        ],
        "sort": [
          {
            "name": "Paling Sesuai",
            "key": "ob",
            "value": "23",
            "inputType": "checkbox",
            "applyFilter": "",
            "__typename": "DASortType",
          },
          {
            "name": "Ulasan",
            "key": "ob",
            "value": "5",
            "inputType": "checkbox",
            "applyFilter": "",
            "__typename": "DASortType",
          },
          {
            "name": "Terbaru",
            "key": "ob",
            "value": "9",
            "inputType": "checkbox",
            "applyFilter": "",
            "__typename": "DASortType",
          },
          {
            "name": "Harga Tertinggi",
            "key": "ob",
            "value": "4",
            "inputType": "checkbox",
            "applyFilter": "",
            "__typename": "DASortType",
          },
          {
            "name": "Harga Terendah",
            "key": "ob",
            "value": "3",
            "inputType": "checkbox",
            "applyFilter": "",
            "__typename": "DASortType",
          },
        ],
        "__typename": "DynamicAttributeDataType",
      },
      "__typename": "DynamicAttributeType",
    },
  },
};

export const TOKOPEDIA_GET_PDP_LAYOUT_RESPONSE = {
  "data": {
    "pdpGetLayout": {
      "name": "Default Layout Desktop",
      "pdpSession":
        '{"sid":903807,"sd":"medstore168","cat":{"id":2184},"cp":{"id":762298,"t":102,"s":true},"opr":36500,"pr":25550,"whid":1123229,"mo":1,"pn":"Hand Sanitizer 500ml Hand Gel Nice Care With Moisturizer Alcohol 70%","st":2,"cn":"new","li":1,"w":0.5,"sf":{},"cr":29,"v":1,"pi":1122990445,"pse":1,"ps":"ACTIVE"}',
      "basicInfo": {
        "alias":
          "hand-sanitizer-500ml-hand-gel-nice-care-with-moisturizer-alcohol-70",
        "isQA": false,
        "id": "1122990445",
        "shopID": "903807",
        "shopName": "medstore168",
        "minOrder": 1,
        "maxOrder": 2,
        "weight": 500,
        "weightUnit": "GRAM",
        "condition": "NEW",
        "status": "ACTIVE",
        "url":
          "https://www.tokopedia.com/medstore168/hand-sanitizer-500ml-hand-gel-nice-care-with-moisturizer-alcohol-70",
        "needPrescription": false,
        "catalogID": "0",
        "isLeasing": false,
        "isBlacklisted": false,
        "menu": {
          "id": "2698920",
          "name": "Alkes",
          "url": "https://www.tokopedia.com/medstore168/etalase/alkes-1",
          "__typename": "pdpMenu",
        },
        "category": {
          "id": "2184",
          "name": "Hand Sanitizer",
          "title": "Hand Sanitizer",
          "breadcrumbURL":
            "https://www.tokopedia.com/p/perawatan-tubuh/perawatan-kaki-tangan/hand-sanitizer",
          "isAdult": false,
          "isKyc": false,
          "minAge": 0,
          "detail": [{
            "id": "2133",
            "name": "Perawatan Tubuh",
            "breadcrumbURL": "https://www.tokopedia.com/p/perawatan-tubuh",
            "isAdult": false,
            "__typename": "pdpCategoryDetail",
          }, {
            "id": "2149",
            "name": "Perawatan Kaki \u0026 Tangan",
            "breadcrumbURL":
              "https://www.tokopedia.com/p/perawatan-tubuh/perawatan-kaki-tangan",
            "isAdult": false,
            "__typename": "pdpCategoryDetail",
          }, {
            "id": "2184",
            "name": "Hand Sanitizer",
            "breadcrumbURL":
              "https://www.tokopedia.com/p/perawatan-tubuh/perawatan-kaki-tangan/hand-sanitizer",
            "isAdult": false,
            "__typename": "pdpCategoryDetail",
          }],
          "__typename": "pdpCategory",
        },
        "txStats": {
          "transactionSuccess": "47",
          "transactionReject": "0",
          "countSold": "78",
          "paymentVerified": "51",
          "itemSoldFmt": "80+",
          "__typename": "txStats",
        },
        "stats": {
          "countView": "2472",
          "countReview": "29",
          "countTalk": "0",
          "rating": 4.8,
          "__typename": "pdpStats",
        },
        "__typename": "pdpBasicInfo",
      },
      "components": [{
        "name": "product_media",
        "type": "product_media",
        "position": "[0,0,1,4]",
        "data": [{
          "media": [{
            "type": "image",
            "urlThumbnail":
              "https://images.tokopedia.net/img/cache/200-square/product-1/2020/8/24/7569050/7569050_c85c60aa-2a48-4bc4-94ac-b70ee5e8769c_700_700",
            "videoUrl": "",
            "prefix": "https://images.tokopedia.net/img/cache/",
            "suffix":
              "/product-1/2020/8/24/7569050/7569050_c85c60aa-2a48-4bc4-94ac-b70ee5e8769c_700_700",
            "description": "",
            "__typename": "pdpContentSnapshotMedia",
          }, {
            "type": "image",
            "urlThumbnail":
              "https://images.tokopedia.net/img/cache/200-square/product-1/2020/8/24/7569050/7569050_6ecf0403-746b-4edc-8067-9d4715beee92_700_700",
            "videoUrl": "",
            "prefix": "https://images.tokopedia.net/img/cache/",
            "suffix":
              "/product-1/2020/8/24/7569050/7569050_6ecf0403-746b-4edc-8067-9d4715beee92_700_700",
            "description": "",
            "__typename": "pdpContentSnapshotMedia",
          }, {
            "type": "image",
            "urlThumbnail":
              "https://images.tokopedia.net/img/cache/200-square/product-1/2020/8/24/7569050/7569050_ba8162dc-7088-4860-9be3-7af43bf8ceba_700_700",
            "videoUrl": "",
            "prefix": "https://images.tokopedia.net/img/cache/",
            "suffix":
              "/product-1/2020/8/24/7569050/7569050_ba8162dc-7088-4860-9be3-7af43bf8ceba_700_700",
            "description": "",
            "__typename": "pdpContentSnapshotMedia",
          }, {
            "type": "image",
            "urlThumbnail":
              "https://images.tokopedia.net/img/cache/200-square/product-1/2020/8/24/7569050/7569050_3ae56562-fc8c-4eb2-a154-897c9f132f06_700_700",
            "videoUrl": "",
            "prefix": "https://images.tokopedia.net/img/cache/",
            "suffix":
              "/product-1/2020/8/24/7569050/7569050_3ae56562-fc8c-4eb2-a154-897c9f132f06_700_700",
            "description": "",
            "__typename": "pdpContentSnapshotMedia",
          }, {
            "type": "image",
            "urlThumbnail":
              "https://images.tokopedia.net/img/cache/200-square/product-1/2020/8/24/7569050/7569050_601ebc8e-8d42-4360-a87f-8055baf2f46c_700_700",
            "videoUrl": "",
            "prefix": "https://images.tokopedia.net/img/cache/",
            "suffix":
              "/product-1/2020/8/24/7569050/7569050_601ebc8e-8d42-4360-a87f-8055baf2f46c_700_700",
            "description": "",
            "__typename": "pdpContentSnapshotMedia",
          }],
          "videos": [],
          "__typename": "pdpDataProductMedia",
        }],
        "__typename": "pdpComponent",
      }, {
        "name": "ticker_info",
        "type": "ticker_info",
        "position": "[1,0,1,1]",
        "data": [],
        "__typename": "pdpComponent",
      }, {
        "name": "variant_options",
        "type": "variant",
        "position": "[2,0,1,4]",
        "data": [],
        "__typename": "pdpComponent",
      }, {
        "name": "product_content",
        "type": "product_content",
        "position": "[1,1,1,1]",
        "data": [{
          "name":
            "Hand Sanitizer 500ml Hand Gel Nice Care With Moisturizer Alcohol 70%",
          "price": {
            "value": 25550,
            "currency": "IDR",
            "__typename": "pdpContentSnapshotPrice",
          },
          "campaign": {
            "campaignID": "762298",
            "campaignType": "102",
            "campaignTypeName": "Kejar Diskon Spesial",
            "campaignIdentifier": 1,
            "background": "#2cb846",
            "percentageAmount": 30,
            "originalPrice": 36500,
            "discountedPrice": 25550,
            "originalStock": 10,
            "stock": 2,
            "stockSoldPercentage": 80,
            "threshold": 7,
            "startDate": "2022-06-13 00:00:00",
            "endDate": "2022-06-13 07:59:00",
            "endDateUnix": "1655081940",
            "appLinks": "https://tokopedia.link/kBpwDNVRNqb",
            "isAppsOnly": true,
            "isActive": true,
            "hideGimmick": false,
            "__typename": "pdpContentSnapshotCampaign",
          },
          "thematicCampaign": {
            "additionalInfo": "",
            "background": "",
            "campaignName": "",
            "icon": "",
            "__typename": "pdpContentSnapshotThematicCampaign",
          },
          "stock": {
            "useStock": true,
            "value": "2",
            "stockWording": "Segera Habis",
            "__typename": "pdpContentSnapshotStock",
          },
          "variant": {
            "isVariant": false,
            "parentID": "0",
            "__typename": "pdpContentSnapshotVariant",
          },
          "wholesale": [],
          "isCashback": {
            "percentage": 0,
            "__typename": "pdpContentSnapshotIsCashback",
          },
          "isTradeIn": false,
          "isOS": false,
          "isPowerMerchant": true,
          "isWishlist": false,
          "isCOD": false,
          "isFreeOngkir": {
            "isActive": false,
            "__typename": "pdpContentSnapshotFreeOngkir",
          },
          "preorder": {
            "duration": 0,
            "timeUnit": "UNKNOWN",
            "isActive": false,
            "preorderInDays": 0,
            "__typename": "pdpContentSnapshotPreorder",
          },
          "__typename": "pdpDataProductContent",
        }],
        "__typename": "pdpComponent",
      }, {
        "name": "product_detail",
        "type": "product_detail",
        "position": "[1,2,1,1]",
        "data": [{
          "content": [{
            "title": "Kondisi",
            "subtitle": "Baru",
            "applink": "",
            "showAtFront": true,
            "isAnnotation": false,
            "__typename": "pdpContentProductDetail",
          }, {
            "title": "Berat",
            "subtitle": "500 Gram",
            "applink": "",
            "showAtFront": false,
            "isAnnotation": false,
            "__typename": "pdpContentProductDetail",
          }, {
            "title": "Min. Pemesanan",
            "subtitle": "1 Buah",
            "applink": "",
            "showAtFront": true,
            "isAnnotation": false,
            "__typename": "pdpContentProductDetail",
          }, {
            "title": "Kategori",
            "subtitle": "Hand Sanitizer",
            "applink":
              "https://www.tokopedia.com/p/perawatan-tubuh/perawatan-kaki-tangan/hand-sanitizer",
            "showAtFront": false,
            "isAnnotation": false,
            "__typename": "pdpContentProductDetail",
          }, {
            "title": "Etalase",
            "subtitle": "Alkes",
            "applink": "https://www.tokopedia.com/medstore168/etalase/alkes-1",
            "showAtFront": true,
            "isAnnotation": false,
            "__typename": "pdpContentProductDetail",
          }, {
            "title": "Deskripsi",
            "subtitle":
              "Deskripsi Hand Sanitizer 500ml Hand Gel Nice Care With Moisturizer Alcohol 70%\nNice Care Hand Sanitizer Cair Alcohol 70% yang dilengkapi dengan moisturizer, membunuh kuman, bakteri dan virus serta menjaga kulit dan tangan tetap halus, lembut.\n\nAmpuh :\n- Efektif membunuh bakteri/virus secara instan 100%\n- Melindungi tangan dari bakteri,virus \u0026amp; kuman\n- Tidak perlu membilas tangan dengan air\n- Melembabkan tangan dengan ekstrak lidah buaya\n\nKemasan Botol 500ml\n\nUntuk pengiriman super aman dan terhindar dari kerusakan saat pengiriman, kami anjurkan supaya membeli item tambahan yaitu ekstra packing bubblewrap atau kardus, bisa di cek di link berikut.\nhttps://www.tokopedia.com/medstore168/extra-packing-tambahan-bubblewrap-karton-untuk-order-aman-barang-kaca-bubbledankarton",
            "applink": "",
            "showAtFront": true,
            "isAnnotation": false,
            "__typename": "pdpContentProductDetail",
          }],
          "__typename": "pdpDataProductDetail",
        }],
        "__typename": "pdpComponent",
      }, {
        "name": "obat_keras",
        "type": "custom_info",
        "position": "[1,3,1,1]",
        "data": [],
        "__typename": "pdpComponent",
      }, {
        "name": "shop_credibility",
        "type": "shop_credibility",
        "position": "[1,4,1,1]",
        "data": [],
        "__typename": "pdpComponent",
      }, {
        "name": "shipment",
        "type": "shipment",
        "position": "[1,5,1,1]",
        "data": [],
        "__typename": "pdpComponent",
      }, {
        "name": "shipping",
        "type": "info",
        "position": "[1,6,1,1]",
        "data": [{
          "icon": "",
          "title": "Kurir",
          "isApplink": true,
          "applink": "",
          "content": [],
          "__typename": "pdpDataInfo",
        }],
        "__typename": "pdpComponent",
      }, {
        "name": "shop_voucher",
        "type": "shop_voucher",
        "position": "[1,7,1,1]",
        "data": [],
        "__typename": "pdpComponent",
      }, {
        "name": "offerings",
        "type": "offerings",
        "position": "[1,8,1,1]",
        "data": [],
        "__typename": "pdpComponent",
      }, {
        "name": "installment_paylater",
        "type": "info",
        "position": "[1,9,1,1]",
        "data": [{
          "icon":
            "https://ecs7.tokopedia.net/pdp/info/icon/pdp-paylatercicilan@3x.png",
          "title": "Paylater \u0026 Cicilan",
          "isApplink": true,
          "applink":
            "tokopedia://fintech/paylater?category=Hand+Sanitizer\u0026price=25550.000000\u0026productID=1122990445\u0026productURL=https%3A%2F%2Fwww.tokopedia.com%2Fmedstore168%2Fhand-sanitizer-500ml-hand-gel-nice-care-with-moisturizer-alcohol-70\u0026userID=5136847",
          "content": [],
          "__typename": "pdpDataInfo",
        }],
        "__typename": "pdpComponent",
      }, {
        "name": "QRCode",
        "type": "Web2App",
        "position": "[1,10,1,1]",
        "data": [],
        "__typename": "pdpComponent",
      }, {
        "name": "wholesale",
        "type": "info",
        "position": "[1,11,1,1]",
        "data": [{
          "icon": "",
          "title": "Harga Grosir",
          "isApplink": true,
          "applink": "",
          "content": [],
          "__typename": "pdpDataInfo",
        }],
        "__typename": "pdpComponent",
      }, {
        "name": "protection",
        "type": "info",
        "position": "[1,12,1,1]",
        "data": [{
          "icon":
            "https://ecs7.tokopedia.net/pdp/info/icon/pdp-protection@3x.png",
          "title": "Proteksi Gadget",
          "isApplink": false,
          "applink": "",
          "content": [],
          "__typename": "pdpDataInfo",
        }],
        "__typename": "pdpComponent",
      }, {
        "name": "report",
        "type": "report",
        "position": "[1,13,1,1]",
        "data": [],
        "__typename": "pdpComponent",
      }, {
        "name": "review",
        "type": "review",
        "position": "[0,14,2,1]",
        "data": [],
        "__typename": "pdpComponent",
      }, {
        "name": "tdn_topads",
        "type": "banner_ads",
        "position": "[0,15,2,1]",
        "data": [],
        "__typename": "pdpComponent",
      }, {
        "name": "discussion_faq",
        "type": "discussion_faq",
        "position": "[0,16,2,1]",
        "data": [],
        "__typename": "pdpComponent",
      }, {
        "name": "pdp_1",
        "type": "product_list",
        "position": "[0,17,3,1]",
        "data": [],
        "__typename": "pdpComponent",
      }, {
        "name": "pdp_2",
        "type": "product_list",
        "position": "[0,18,3,1]",
        "data": [],
        "__typename": "pdpComponent",
      }, {
        "name": "pdp_3",
        "type": "product_list",
        "position": "[0,19,3,1]",
        "data": [],
        "__typename": "pdpComponent",
      }, {
        "name": "pdp_4",
        "type": "product_list",
        "position": "[0,20,3,1]",
        "data": [],
        "__typename": "pdpComponent",
      }],
      "__typename": "pdpLayout",
    },
  },
};

export const TOKOPEDIA_GET_RECOMMENDED_PRODUCTS_RESPONSE = {
  "data": {
    "get_home_recommendation": {
      "recommendation_tabs": [{
        "id": 1,
        "name": "For Kelvin",
        "imageUrl":
          "https://images.tokopedia.net/img/cache/100/attachment/2019/10/8/40768394/40768394_8989ef25-ee3b-4510-89bb-fc894078954c.jpg",
        "__typename": "RecommendationTabs",
      }, {
        "id": 2,
        "name": "Men In Style",
        "imageUrl":
          "https://images.tokopedia.net/img/cache/100/ndZFpx/2022/6/10/c4c35dec-891d-4ae9-ae99-759705ed2510.jpg",
        "__typename": "RecommendationTabs",
      }, {
        "id": 3,
        "name": "Special Discount",
        "imageUrl":
          "https://images.tokopedia.net/img/cache/100/attachment/2019/10/8/40768394/40768394_1629133d-4c08-467c-aed0-bd8e82c7ea40.jpg",
        "__typename": "RecommendationTabs",
      }, {
        "id": 4,
        "name": "Aktivitasmu",
        "imageUrl":
          "https://images.tokopedia.net/img/cache/100/ndZFpx/2022/3/10/bf82d076-cf05-48bf-a6cf-92a981091b0b.jpg",
        "__typename": "RecommendationTabs",
      }, {
        "id": 5,
        "name": "Suplemen Fitnes",
        "imageUrl":
          "https://images.tokopedia.net/img/cache/100/attachment/2019/11/7/75545163/75545163_f6ac6050-3872-48e8-b445-02a33e346061.jpg",
        "__typename": "RecommendationTabs",
      }, {
        "id": 6,
        "name": "Tempat Roti",
        "imageUrl":
          "https://images.tokopedia.net/img/cache/100/attachment/2019/10/23/40768394/40768394_6a24460c-fbc2-40ab-bea6-3e557474f1d7.jpg",
        "__typename": "RecommendationTabs",
      }, {
        "id": 7,
        "name": "CD PlayStation",
        "imageUrl":
          "https://images.tokopedia.net/img/cache/100/attachment/2019/10/23/40768394/40768394_7c9ad641-8a48-4b63-a4cc-cae37bbcaae1.jpg",
        "__typename": "RecommendationTabs",
      }],
      "recommendation_product": {
        "pageName": "homepage",
        "product": [{
          "id": 2488322207,
          "name":
            "PI KANG SHUANG KRIM 5 GRAM/MICONAZOLE/ANTI JAMU/KADAS/KURAP/PANU",
          "category": "Kesehatan/Obat - Obatan/Obat Kulit",
          "url":
            "https://www.tokopedia.com/apotekyopelembang/pi-kang-shuang-krim-5-gram-miconazole-anti-jamu-kadas-kurap-panu?src=topads",
          "clickUrl":
            "https://ta.tokopedia.com/promo/v1/clicks/8a-xgVY2gmUEH_HNHA1NHpyabm-xgVY789CBUsthbm-FQRo2PcB5QiUEHZFiPcBWgZUEH_yOo_ndHAjhoiFiyRCsUst7HAnFbm-xgVYpyfYagZUEHpedbsHRoAedosJR6A1hHpyDUSHp9fh5gaUEUMuNZM2jZJ2M33NGPMep_Mh-qMY2_1o-r7BW_sCsQABE3BPc8ujagfBvq1BRZ3BRq3JausujHsBN3jyN8Bja69Bq17jfZ32Cq1hAZSuiHsuk3Bo-ojBk3_V6uV1a3uzCH1h9uM268Bu7_jzS8jY_HAz6qB-W_VPo8V21e_-qzJud_1zuoVB2Z9o-Q_BNyuPjrc-D63Wq3J-MyuPzq1Y2Z9P-q9P2ysoGrVtaQIuyH7-Nys-ZHujp1MgxuOV2_fB-P7B2PfBiH72F3s-DPuKp_MYiH7-MyuPzq1Y2Z9P-q9P2yOx3QcoXQcgjz7gXyRB-ojB2Z9o-QjNkysoGQVKaZSBiHfzE3Bo-ojBk__CvepzE_S2zHJYJ39x68Mrh_uzoHjB2PfBsHjNfyfO3gMHauMxsQ1N5Z325q1Nkz9PHqjJO_320HjOEqRxouVVR_320q3gzv_7ibm-Orfua9fBjUstio_JposK7oaUDUSoBrRo2QfNwq3ei6i-EZaOiq7VcZcOzuAHFuVxVP9Cdrsuy39epPaO2rJBeQsB9qug9HV4RrJoAQfWw1IBcuMuZu7hR1JNXZ_VwQpVWzBzs3suyq_P3ysBse3hJ8czR9OgtbuVHPcOHPjByuJhp1Iov_1PdPjHpQV1Ro7Wv6JhJuJDOzACxqpBpHpzmomUDUMVDgaUEUMoDP9o7g9-wPs-wrMusg3N7PMBBPaUDUMNOQ3-BrBY5gBYxgIHi6sKDUMNOQ3-BrBYxgIowrMuhUstdbm-sy9zwq3zpUs2QopJObAUaopjDHsUNoO7DUMNwyfVXgcBjy9zB9fVjraUEoAjDUMVi9RzBrRei6i-6UiFircYpPVYxQcri6i-jg3yibm-fg9-pq3YXUstiPsUibm-sQIupPcua9fBj9RyaUsthHpypbm-FrMBsguYiq3ei6seFHAnDUMP5y3hwq3ei6soY?r=https%3A%2F%2Fwww.tokopedia.com%2Fapotekyopelembang%2Fpi-kang-shuang-krim-5-gram-miconazole-anti-jamu-kadas-kurap-panu%3Fsrc%3Dtopads&page=1&ob=0&dv=desktop-0.0&management_type=1&src=recom_widget_homepage&t=desktop-0.0",
          "clusterID": 1363,
          "isWishlist": false,
          "imageURL":
            "https://images.tokopedia.net/img/cache/200-square/hDjmkQ/2021/12/1/cdedad3b-c1ea-4021-8ab7-7a09b40e495f.jpg",
          "isTopads": true,
          "trackerImageUrl":
            "https://ta.tokopedia.com/promo/v1/views/8a-2rOYDQfPwgcV7yZUEHZFiy3zwq3ei6sJp6_nO6_HfHiFiy3zwPIBFgZUEHZFircYpq9z2Qfdi6sJDUSz2Q31i6sJfo_1F6AnNH_yDUSCxPcKi6i-2Q3VSg9HXPcY0QRCBgcBxbMNBPmY2Q3r5yfVsqc15Hs1Fb9ohP3VagZYtzc2WqOJ5HsnaHZ4hHi4hbfojg3zxgAoib3Hhg3JWoAnaHZ7dy3URb_PxHABioACBoAjOgiNkrcribm-xgVYpyfYagZUEHpedbsHRoAedosJR6A1hHpyDUSHp9fh5gaUEUMuNZM2jZJ2M33NGPMep_Mh-qMY2_1o-r7BW_sCsQABE3BPc8ujagfBvq1BRZ3BRq3JausujHsBN3jyN8Bja69Bq17jfZ32Cq1hAZSuiHsuk3Bo-ojBk3_V6uV1a3uzCH1h9uM268Bu7_jzS8jY_HAz6qB-W_VPo8V21e_-qzJud_1zuoVB2Z9o-Q_BNyuPjrc-D63Wq3J-MyuPzq1Y2Z9P-q9P2ysoGrVtaQIuyH7-Nys-ZHujp1MgxuOV2_fB-P7B2PfBiH72F3s-DPuKp_MYiH7-MyuPzq1Y2Z9P-q9P2yOx3QcoXQcgjz7gXyRB-ojB2Z9o-QjNkysoGQVKaZSBiHfzE3Bo-ojBk__CvepzE_S2zHJYJ39x68Mrh_uzoHjB2PfBsHjNfyfO3gMHauMxsQ1N5Z325q1Nkz9PHqjJO_320HjOEqRxouVVR_320q3gzv_7ibm-Orfua9fBjUstio_JposK7oaUDUSoBrRo2QfNwq3ei6i-EZaOiq7VcZcOzuAHFuVxVP9Cdrsuy39epPaO2rJBeQsB9qug9HV4RrJoAQfWw1IBcuMuZu7hR1JNXZ_VwQpVWzBzs3suyq_P3ysBse3hJ8czR9OgtbuVHPcOHPjByuJhp1Iov_1PdPjHpQV1Ro7Wv6JhJuJDOzACxqpBpHpzmomUDUMVDgaUEUMoDP9o7g9-wPs-wrMusg3N7PMBBPaUDUMNOQ3-BrBY5gBYxgIHi6sKDUMNOQ3-BrBYxgIowrMuhUstdbm-X9foxQMz2gcV7guYxgIHi6seNbm-xyBY7g9o7Usti_iUDUSC5rRzwy3hSUs2QUMzBgi-Pbm-fg9-pq3YXUstiPsUibm-sQIupPcua9fBj9RyaUsthHpypbm-FrMBsguYiq3ei6seFHAnDUMP5y3hwq3ei6soY?page=1&src=recom_widget_homepage&ob=0&t=desktop-0.0&management_type=1&dv=desktop-0.0",
          "price": "Rp11.423",
          "priceInt": 11423,
          "slashedPrice": "",
          "slashedPriceInt": 0,
          "discountPercentage": 0,
          "isRating": true,
          "rating": 5,
          "ratingAverage": "5.0",
          "countReview": 24,
          "recommendationType": "cluster_v2_recentview",
          "isShop": false,
          "shop": {
            "shopID": 12668266,
            "name": "Apotek Yope Lembang",
            "url":
              "https://ta.tokopedia.com/promo/v1/clicks/8a-xgVY2gmUEH_HNHA1NHpyabm-xgVY789CBUsthbm-FQRo2PcB5QiUEHZFiPcBWgZUEH_yOo_ndHAjhoiFiyRCsUst7HAnFbm-xgVYpyfYagZUEHpedbsHRoAedosJR6A1hHpyDUSHp9fh5gaUEUMuNZM2jZJ2M33NGPMep_Mh-qMY2_1o-r7BW_sCsQABE3BPc8ujagfBvq1BRZ3BRq3JausujHsBN3jyN8Bja69Bq17jfZ32Cq1hAZSuiHsuk3Bo-ojBk3_V6uV1a3uzCH1h9uM268Bu7_jzS8jY_HAz6qB-W_VPo8V21e_-qzJud_1zuoVB2Z9o-Q_BNyuPjrc-D63Wq3J-MyuPzq1Y2Z9P-q9P2ysoGrVtaQIuyH7-Nys-ZHujp1MgxuOV2_fB-P7B2PfBiH72F3s-DPuKp_MYiH7-MyuPzq1Y2Z9P-q9P2yOx3QcoXQcgjz7gXyRB-ojB2Z9o-QjNkysoGQVKaZSBiHfzE3Bo-ojBk__CvepzE_S2zHJYJ39x68Mrh_uzoHjB2PfBsHjNfyfO3gMHauMxsQ1N5Z325q1Nkz9PHqjJO_320HjOEqRxouVVR_320q3gzv_7ibm-Orfua9fBjUstio_JposK7oaUDUSoBrRo2QfNwq3ei6i-EZaOiq7VcZcOzuAHFuVxVP9Cdrsuy39epPaO2rJBeQsB9qug9HV4RrJoAQfWw1IBcuMuZu7hR1JNXZ_VwQpVWzBzs3suyq_P3ysBse3hJ8czR9OgtbuVHPcOHPjByuJhp1Iov_1PdPjHpQV1Ro7Wv6JhJuJDOzACxqpBpHpzmomUDUMVDgaUEUMoDP9o7g9-wPs-wrMusg3N7PMBBPaUDUMNOQ3-BrBY5gBYxgIHi6sKDUMNOQ3-BrBYxgIowrMuhUstdbm-sy9zwq3zpUs2QopJObAUaopjDHsUNoO7DUMNwyfVXgcBjy9zB9fVjraUEoAjDUMVi9RzBrRei6i-6UiFircYpPVYxQcri6i-jg3yibm-fg9-pq3YXUstiPsUibm-sQIupPcua9fBj9RyaUsthHpypbm-FrMBsguYiq3ei6seFHAnDUMP5y3hwq3ei6soY?src=recom_widget_homepage&dv=desktop-0.0&r=https%3A%2F%2Fwww.tokopedia.com%2Fapotekyopelembang&management_type=1&t=desktop-0.0&uid=5136847&page=1",
            "city": "Bandung",
            "__typename": "RecommendationShop",
          },
          "labelGroups": [
            {
              "type": "textDarkGrey",
              "title": "Terjual 100+",
              "position": "integrity",
              "url": "",
              "__typename": "RecommendationProductLabelGroup",
            },
          ],
          "badges": [
            {
              "title": "Official Store",
              "image_url":
                "https://images.tokopedia.net/ta/icon/badge/OS-Badge-80.png",
              "__typename": "RecommendationProductBadge",
            },
          ],
          "__typename": "RecommendationProduct",
        }],
        "banner": [],
        "position": [
          { "type": "product", "__typename": "RecommendationPosition" },
        ],
        "hasNextPage": false,
        "__typename": "RecommendationProductData",
      },
      "__typename": "HomeRecommendationData",
    },
  },
};

export const TOKOPEDIA_ACE_SEARCH_V4_RESPONSE = {
  "data": {
    "ace_search_product_v4": {
      "header": {
        "totalData": 113,
        "totalDataText": "113",
        "processTime": 0.051258072,
        "responseCode": 0,
        "errorMessage": "",
        "additionalParams": "",
        "keywordProcess": "0",
        "componentId": "01.02.02.01",
        "__typename": "AceSearchUnifyHeader",
      },
      "data": {
        "backendFilters": "",
        "isQuerySafe": true,
        "ticker": {
          "text": "",
          "query": "",
          "typeId": 0,
          "componentId": "",
          "trackingOption": 0,
          "__typename": "AceSearchUnifyTicker",
        },
        "redirection": {
          "redirectUrl": "",
          "departmentId": 0,
          "__typename": "AceSearchUnifyRedirection",
        },
        "related": {
          "position": 0,
          "trackingOption": 0,
          "relatedKeyword": "",
          "otherRelated": [],
          "__typename": "AceSearchUnifyRelated",
        },
        "suggestion": {
          "currentKeyword": "polygon stratos s7",
          "suggestion": "",
          "suggestionCount": 0,
          "instead": "",
          "insteadCount": 0,
          "query": "",
          "text": "",
          "componentId": "",
          "trackingOption": 0,
          "__typename": "AceSearchUnifySuggestion",
        },
        "products": [
          {
            "id": 2026520766,
            "name": "Polygon Stratos S7 Fully Upgrade Di2",
            "ads": {
              "adsId": "",
              "productClickUrl": "",
              "productWishlistUrl": "",
              "productViewUrl": "",
              "__typename": "AceSearchUnifyAds",
            },
            "badges": [
              {
                "title": "Power Badge",
                "imageUrl":
                  "https://images.tokopedia.net/img/power_merchant_badge.png",
                "show": true,
                "__typename": "AceSearchUnifyBadge",
              },
            ],
            "category": 3497,
            "categoryBreadcrumb": "olahraga/sepeda/sepeda-balap",
            "categoryId": 62,
            "categoryName": "Olahraga",
            "countReview": 0,
            "customVideoURL": "",
            "discountPercentage": 0,
            "gaKey":
              "/searchproduct/olahraga/sepeda/sepeda-balap/polygon+stratos+s7/ud-laju/polygon-stratos-s7-fully-upgrade-di2",
            "imageUrl":
              "https://images.tokopedia.net/img/cache/200-square/hDjmkQ/2021/7/26/36574ac7-cc9b-4a2d-a3fd-484a56364307.jpg",
            "labelGroups": [],
            "originalPrice": "",
            "price": "Rp39.468.000",
            "priceRange": "",
            "rating": 0,
            "ratingAverage": "",
            "shop": {
              "shopId": 8993444,
              "name": "UD Laju",
              "url": "https://www.tokopedia.com/ud-laju",
              "city": "Jakarta Pusat",
              "isOfficial": false,
              "isPowerBadge": true,
              "__typename": "AceSearchUnifyShop",
            },
            "url":
              "https://www.tokopedia.com/ud-laju/polygon-stratos-s7-fully-upgrade-di2?extParam=ivf%3Dfalse",
            "wishlist": false,
            "sourceEngine": "0",
            "__typename": "AceSearchUnifyProduct",
          },
        ],
        "violation": {
          "headerText": "",
          "descriptionText": "",
          "imageURL": "",
          "ctaURL": "",
          "ctaApplink": "",
          "buttonText": "",
          "buttonType": "",
          "__typename": "AceSearchUnifyViolation",
        },
        "__typename": "AceSearchUnifyData",
      },
      "__typename": "AceSearchUnifyResponse",
    },
  },
};
