name: Flat

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    #- cron: '*/5 * * * *'
    - cron: '0 7 * * *'

jobs:
  # split 40 jobs to 4 jobs with 10 item each
  recommended_products:
    strategy:
      max-parallel: 1
      matrix:
        index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        include:
          - index: 0
            GH_TOKEN: GH_TOKEN_0
          - index: 1
            GH_TOKEN: GH_TOKEN_1
          - index: 2
            GH_TOKEN: GH_TOKEN_2
          - index: 3
            GH_TOKEN: GH_TOKEN_3
          - index: 4
            GH_TOKEN: GH_TOKEN_4
          - index: 5
            GH_TOKEN: GH_TOKEN_5
          - index: 6
            GH_TOKEN: GH_TOKEN_6
          - index: 7
            GH_TOKEN: GH_TOKEN_7
          - index: 8
            GH_TOKEN: GH_TOKEN_8
          - index: 9
            GH_TOKEN: GH_TOKEN_9

    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.22.x

      - name: Checkout code
        uses: actions/checkout@master

      - name: Fetch Tokopedia Recommended Product
        run: |
           echo HTTP_PROXY=$HTTP_PROXY >> .env
           echo GH_TOKEN=$GH_TOKEN >> .env
           export $(cat .env | xargs)
           deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable cli/daily_products.ts '${{matrix.index}}'
        env:
          GH_TOKEN: ${{ secrets[matrix.GH_TOKEN] }}
          HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
